### PR TITLE
app.options doesn't exist when used in addons

### PR DESCRIPTION
**Pull request by wagenet**

### CODE REVIEW

**Comment by pangratz** [comment]
Thanks! I guess this is OK to merge, but I'm still struggling to reproduce the issue reported in #2 so future regressions are caught. So the use case is an ember addon `test-addon` which uses the `ember-cli-htmlbars-inline-precompile` addon, and `test-addon` is used in an ember cli app `test-app`. And then `ember build` within the `test-app` should fail, right?

**Comment by wagenet** [comment]
I don't actually know if `ember build` fails, but I do get failures with ember server.

**Comment by pangratz** [comment]
I wonder if we should fetch the specific object to get the options from with the same logic as used in [`ember-cli-babel/index.js`](https://github.com/babel/ember-cli-babel/blob/5bde7459ef00811a13cf64c28660bd0f33f81a34/index.js#L33-L34).

Maybe someone of the `ember-cli-babel` maintainers can chime in and clarify what would be the best way to override/enhance the options for babel ...

cc @stefanpenner @rwjblue @gordonkristan

**Comment by pangratz** [comment]
Related ember-cli/ember-cli/issues/4031

**Comment by pangratz** [comment]
@wagenet I tend to close this PR in favor of #7, as this would be a more Ember-CLI idiomatic way to address this problem. Thanks for raising the issue though. Cheers!

**Comment by wagenet** [comment]
@pangratz I have no objections to closing it as long as we end up with a solution for this case :)
I just sent this PR as it's the hack I used to make things work in my app.

**Pull request merged**
